// Vercel Serverless Function for Scribe's Sanctuary Story Generation
// Path: /api/generate-story.js

export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  // Handle preflight OPTIONS request
  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  const { keywords } = req.body;

  if (!keywords || !Array.isArray(keywords) || keywords.length !== 5) {
    return res.status(400).json({ error: 'Please provide an array of exactly 5 keywords.' });
  }

  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    console.error("Server Configuration Error: GEMINI_API_KEY is not defined.");
    return res.status(500).json({ 
      error: 'Story Generator is currently offline. Administrator needs to configure the GEMINI_API_KEY.' 
    });
  }

  const prompt = `Write a beautiful, engaging short story of approximately 500 words. 
  It must be highly readable, written in a warm and classic prose style (suitable for all ages), and teach a clear moral lesson.
  
  The story MUST prominently feature and revolve around these five keywords: ${keywords.join(', ')}.

  Format your response STRICTLY as a JSON object with exactly these three keys:
  {
    "title": "Title of the Story",
    "story": "The complete short story content, structured with multiple paragraphs (using \\n\\n for paragraph breaks).",
    "moral": "The moral lesson of the story stated in one concise, elegant sentence."
  }
  
  Ensure there is no surrounding markdown, no backticks, and no extra text outside the JSON object.`;

  try {
    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(geminiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt
              }
            ]
          }
        ],
        generationConfig: {
          responseMimeType: 'application/json'
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API Error Response:", errorText);
      throw new Error(`Gemini API responded with status ${response.status}`);
    }

    const data = await response.json();
    
    if (!data.candidates || data.candidates.length === 0 || !data.candidates[0].content) {
      throw new Error("No content generated by Gemini.");
    }

    const textResponse = data.candidates[0].content.parts[0].text;
    
    // Parse to ensure it is valid JSON before returning
    const parsedStory = JSON.parse(textResponse.trim());
    
    return res.status(200).json(parsedStory);
  } catch (err) {
    console.error("Error in generate-story serverless function:", err);
    return res.status(500).json({ 
      error: 'The scribes failed to weave the tale. Please verify your keys and keywords.' 
    });
  }
}
